<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'api/report/getReport',
        'api/report/getTraffic',
        'api/inquiry-popup',
        'api/ask-us-inquiry',
        'api/prefer',
        'nosay/report/getStatistics',
        'nosay/wechatLogin',
        'payment/alipay/ipn',
        'payment/paypalStandard/ipn'
    ];

    public function handle($request, Closure $next)
    {
        if (in_array($request->path(),$this->except)){
            return  $next($request);
        }
        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }
}
