<?php


namespace App\Modules\Setting\Models;

use App\Traits\ModelBoot;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;

class Setting extends Model implements TranslatableContract
{
    use HasFactory, Translatable, ModelBoot;

    const MODEL_TYPE = 'setting';

    protected $casts = [
        'whatsapp_float_data' => 'json'
    ];

    public $translatedAttributes = [
        'name',
        'title',
        'keywords',
        'description',
        'seo_product_title',
        'seo_product_description',
        'seo_product_keywords',
        'seo_products_title',
        'seo_products_description',
        'seo_products_keywords',
        'seo_product_category_title',
        'seo_product_category_description',
        'seo_product_category_keywords',
        'seo_product_category_bottom_title',
        'seo_product_category_bottom_description',
        'seo_product_category_bottom_keywords',
        'seo_product_tag_title',
        'seo_product_tag_description',
        'seo_product_tag_keywords',
        'seo_blogs_title',
        'seo_blogs_description',
        'seo_blogs_keywords',
        'seo_articles_title',
        'seo_articles_description',
        'seo_articles_keywords',
        'seo_blog_title',
        'seo_blog_description',
        'seo_blog_keywords',
        'seo_article_title',
        'seo_article_description',
        'seo_article_keywords',
        'seo_article_category_title',
        'seo_article_category_description',
        'seo_article_category_keywords',
        'seo_blog_category_title',
        'seo_blog_category_description',
        'seo_blog_category_keywords',
        'seo_blog_tag_title',
        'seo_blog_tag_description',
        'seo_blog_tag_keywords',
        'seo_sitemap_title',
        'seo_sitemap_description',
        'seo_sitemap_keywords',
        'product_alt_template',
        'seo_home_title',
        'seo_home_description',
        'seo_home_keywords',
        'search_placeholder',
        'search_hot_keywords'
    ];

    protected $fillable = [
        'logo',
        'bottom_logo',
        'inner_logo',
        'ico',
        'contract_mobile',
        'contract_email',
        'whatsapp',
        'address',
        'facebook',
        'twitter',
        'skype',
        'chat_status',
        'chat_token',
        'website_token',
        'is_cache',
        'cache_ttl',
        'website_info',
        'template_path',
        'company_address',
        'company_brief',
        'category_product_num',
        'product_list_num',
        'article_list_num',
        'blog_list_num',
        'project_case_list_num',
        'faq_list_num',
        'product_search_list_num',
        'related_product_num',
        'related_article_num',
        'sidebar_product_category_num',
        'sidebar_new_product_num',
        'hot_product_list_num',
        'recommend_product_num',
        'product_tag_num',
        'header_menu_product_category_num',
        'link_num',
        'sensitive_words',
        'head_code',
        'banner_areas',
        'version',
        'mail_mailer',
        'mail_host',
        'mail_port',
        'mail_username',
        'mail_password',
        'mail_encryption',
        'mail_from_address',
        'mail_from_name',
        'mail_addressee',
        'gsg_code',
        'body_code',
        'max_size',
        'size_label',
        'qr_code',
        'qr_code_whatsapp',
        'adwords_token',
        'tag_max_num',
        'watermark',
        'watermark_location',
        'watermark_x',
        'watermark_y',
        'home_lock',
        'home_lock_password',
        'allow_ips',
        'nocaptcha_sitkey',
        'nocaptcha_secret',
        'all_locale_active',
        'upload_image_max_size',
        'ban_ips',
        'ban_emails',
        'switch_editor',
        'ban_access_ips',
        'whatsapp_float_active',
        'whatsapp_float_data',
        'facebook_code',
        'setting_seo_show',
        'product_list_seo_show',
        'product_category_seo_show',
        'product_detail_seo_show',
        'product_tag_seo_show',
        'article_list_seo_show',
        'article_category_seo_show',
        'article_detail_seo_show',
        'blog_list_seo_show',
        'blog_category_seo_show',
        'blog_detail_seo_show',
        'blog_tag_seo_show',
        'is_translate',
        'website_id',
        'upload_name_type',
        'tree_strictly',
        'whatsapp_bottom',
        'product_watermark',
        'blog_watermark',
        'article_watermark',
        'page_watermark',
        'download_watermark',
        'teams_link',
        'operation_guide',
        'login_pwd_encrypt',
        'single_sign_on',
        'gibberish_threshold',
        'inquiry_source_on',
        'postal_code'
    ];
}
